# Request
uint8 finger_target_width           # [mm], 0~100
uint8 finger_width_speed            # [mm/s], 1~200(default:150)
uint8 gripping_force                # [N], 1~100(default:30)
uint8 contact_detection_sesitivity  # 1~100(default:80)
---
# Response
int32 result